name: emotion_music_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+2
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_commons: ^0.6.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.3.2
  sqflite: ^2.2.8+4
  path: ^1.9.1
  path_provider: ^2.0.15
  image_picker: ^0.8.7+5
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/emotion_model.tflite
    - assets/labels.txt
    - assets/music/angry/
    - assets/music/sad/
    - assets/music/fear/
    - assets/music/disgust/
    - assets/images/Cloud.jpg
    - assets/images/vinyl.png
    - assets/images/Forest.jpg
    - assets/images/Butterfly.jpg
    - assets/images/Bird.jpg
    - assets/images/Waterfall.jpg
    - assets/images/River.jpg
    - assets/images/Mushroom.jpg
    - assets/images/River.jpg
    - assets/images/Fire.jpg
    - assets/images/Fire Bottle.jpg
    - assets/images/Fire Guitar.jpg
    - assets/images/Light.jpg
    - assets/images/Heaven.jpg
    - assets/images/Chess.jpg
    - assets/images/Love.jpg
    - assets/images/Victory.jpg